CREATE TABLE Movies
(	
	DATASET_ID INT NOT NULL PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL
);

CREATE TABLE Genres
(	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	GENRES VARCHAR(255) NOT NULL,
	COUNT INT NOT NULL
);

CREATE TABLE Users
(	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL
);

CREATE TABLE Copy
(	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MOVIE_ID INT FOREIGN KEY REFERENCES Movies(DATASET_ID),
	CREATED_AT SMALLDATETIME
);

CREATE TABLE Rent
(	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	COPY_ID INT FOREIGN KEY REFERENCES Copy(ID),
	USER_ID INT FOREIGN KEY REFERENCES Users(ID),
	RENT_DATE DATE NOT NULL,
	RETURN_DATE DATE NOT NULL,
	ACTUAL_RETURN_DATE DATE

);
--Inserindo valores para teste da View de Devoluções Atrasadas.
INSERT INTO Rent VALUES
(5,6,'2021-01-20','2021-01-23','2021-01-26'),
(25,5,'2021-01-21','2021-01-24','2021-01-27');

CREATE TABLE Genres_Link
(	
	MOVIE_ID INT FOREIGN KEY REFERENCES Movies(DATASET_ID),
	GENRE_ID INT FOREIGN KEY REFERENCES Genres(ID)
);

CREATE TABLE Ratings
(	
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MOVIE_ID INT FOREIGN KEY REFERENCES Movies(DATASET_ID),
	RATING FLOAT NOT NULL
);