-- View para saber filmes com devolução em atraso.
CREATE OR ALTER VIEW RENT_DELAY
AS
	SELECT U.NAME, M.TITLE, R.RETURN_DATE 
		FROM Rent R
		JOIN Copy C
		ON C.ID = R.COPY_ID
		JOIN Movies M
		ON M.DATASET_ID = C.MOVIE_ID 	
		JOIN Users U
		ON U.ID = R.USER_ID
		WHERE R.ACTUAL_RETURN_DATE IS NULL
		AND R.RETURN_DATE < GETDATE()
		

-- SELECT * FROM RENT_DELAY;

-- View oara saber devoluções que foram feitas com atraso.
DROP VIEW RENT_DELAY;
CREATE OR ALTER VIEW USERS_DELAYED_RENTS
AS
	SELECT U.NAME, M.TITLE, R.RETURN_DATE, R.ACTUAL_RETURN_DATE 
		FROM Rent R
		JOIN Copy C
		ON C.ID = R.COPY_ID
		JOIN Movies M
		ON M.DATASET_ID = C.MOVIE_ID 	
		JOIN Users U
		ON U.ID = R.USER_ID
		WHERE R.ACTUAL_RETURN_DATE > R.RETURN_DATE 
		

-- SELECT * FROM USERS_DELAYED_RENTS;
